name: RC Ready Issues

on:
  pull_request:
    branches:
      - develop
    types: [synchronize]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-extract-issues@v1.0.0
        with:
          way: 'title'
          issues-labels: 'RC_READY'
          issues-comment: |
            HI! 这个 issue: ${number} 已合到develop。
          issues-close: false
