name: test version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
      - name: auto merge
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'master'
          development_branch: 'develop'
          env:
            GITHUB_TOKEN:
              ${{ secrets.GITHUB_TOKEN }}

