#https://github.com/marketplace/actions/nightly-merge
name: 'Auto Merge'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Auto Merge
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: 'master'
        development_branch: 'develop'
        allow_ff: false
        allow_forks: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
