name: 'Merge'
on:
  push:
    branches:
      - develop
jobs:
  master-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Master to develop
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: 'develop'
        development_branch: 'test'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
