name: Prod Ready Issues

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.merged == true
        uses: actions-cool/pr-extract-issues@v1.0.0
        with:
          way: 'title'
          issues-labels: 'PROD_READY'
          issues-comment: |
            HI! 这个 issue: ${number} 已合到master。
          issues-close: false
          
      - if: github.event.pull_request.merged == false
        run: "echo close"
