name: Prod Ready Issues

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-extract-issues@v1.0.0
        with:
          way: 'commit'
          issues-labels: 'PROD_READY'
          issues-comment: |
            HI! 这个 issue: ${number} 已经被修复了。
          issues-close: false
