#https://github.com/marketplace/actions/github-tag-bump
name: Add Tag
on:
  #workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      run: echo "this head brach $github_head_ref"
      #uses: anothrNick/github-tag-action@1.26.0
      if: ${{ github.head_ref == 'develop' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        
        

        
        

